### ISSUE TITLE
Issue loading DoH/DoL profile

### ISSUE THREAD

**Issue by mr-jak3z** [Angles24/DoH-DoL-Profiles#13]
Trying to load the DoH/DoL profile for 51-63 Botanist/Miner getting this error:

```
[10:14:48.174 N] Loading profile 51-63 Botanist.xml
[10:14:48.286 N] Parsing xml...
[10:14:48.287 N] Failed to load profile: Exception has been thrown by the target of an invocation.
[10:14:48.287 D] System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.TypeInitializationException: The type initializer for 'ExBuddy.OrderBotTags.Behaviors.ExProfileBehavior' threw an exception. ---> System.TypeInitializationException: The type initializer for 'ExBuddy.Helpers.Condition' threw an exception. ---> System.InvalidOperationException: The calling thread cannot access this object because a different thread owns it.
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at System.Windows.Window.get_Title()
   at ExBuddy.Helpers.Condition..cctor() in C:\Users\pc\Desktop\RB\BotBases\ExBuddy\ExBuddy\Helpers\Condition.cs:line 32
   --- End of inner exception stack trace ---
   at ExBuddy.Helpers.Condition.AddNamespacesToScriptManager(String[] param)
   at ExBuddy.OrderBotTags.Behaviors.ExProfileBehavior..cctor() in C:\Users\pc\Desktop\RB\BotBases\ExBuddy\ExBuddy\OrderBotTags\Behaviors\ExProfileBehavior.cs:line 29
   --- End of inner exception stack trace ---
   at ExBuddy.OrderBotTags.Behaviors.ExProfileBehavior..ctor()
   at ExBuddy.OrderBotTags.Gather.ExGatherTag..ctor() in C:\Users\pc\Desktop\RB\BotBases\ExBuddy\ExBuddy\OrderBotTags\Gather\ExGatherTag.cs:line 82
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at Clio.XmlEngine.PropertyProcessor.(PropertyInfo , XElement , Object )
   at Clio.XmlEngine.XmlEngine.Load(Object obj, XElement element)
   at Clio.XmlEngine.PropertyProcessor.(PropertyInfo , XElement , Object )
   at Clio.XmlEngine.XmlEngine.Load(Object obj, XElement element)
   at Clio.XmlEngine.PropertyProcessor.(XElement , Type )
   at Clio.XmlEngine.PropertyProcessor..(XElement )
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Clio.XmlEngine.PropertyProcessor.(XElement , PropertyInfo )
   at Clio.XmlEngine.PropertyProcessor.(PropertyInfo , XElement , Object )
   at Clio.XmlEngine.XmlEngine.Load(Object obj, XElement element)
   at ff14bot.NeoProfiles.NeoProfile.Load(XElement element, String path)
   at ff14bot.NeoProfiles.NeoProfile.Load(String path)
   at ff14bot.NeoProfiles.NeoProfileManager.Load(String profilePath, Boolean rememberPath) --> System.TypeInitializationException: The type initializer for 'ExBuddy.OrderBotTags.Behaviors.ExProfileBehavior' threw an exception. ---> System.TypeInitializationException: The type initializer for 'ExBuddy.Helpers.Condition' threw an exception. ---> System.InvalidOperationException: The calling thread cannot access this object because a different thread owns it.
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at System.Windows.Window.get_Title()
   at ExBuddy.Helpers.Condition..cctor() in C:\Users\pc\Desktop\RB\BotBases\ExBuddy\ExBuddy\Helpers\Condition.cs:line 32
   --- End of inner exception stack trace ---
   at ExBuddy.Helpers.Condition.AddNamespacesToScriptManager(String[] param)
   at ExBuddy.OrderBotTags.Behaviors.ExProfileBehavior..cctor() in C:\Users\pc\Desktop\RB\BotBases\ExBuddy\ExBuddy\OrderBotTags\Behaviors\ExProfileBehavior.cs:line 29
   --- End of inner exception stack trace ---
   at ExBuddy.OrderBotTags.Behaviors.ExProfileBehavior..ctor()
   at ExBuddy.OrderBotTags.Gather.ExGatherTag..ctor() in C:\Users\pc\Desktop\RB\BotBases\ExBuddy\ExBuddy\OrderBotTags\Gather\ExGatherTag.cs:line 82 --> System.TypeInitializationException: The type initializer for 'ExBuddy.Helpers.Condition' threw an exception. ---> System.InvalidOperationException: The calling thread cannot access this object because a different thread owns it.
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at System.Windows.Window.get_Title()
   at ExBuddy.Helpers.Condition..cctor() in C:\Users\pc\Desktop\RB\BotBases\ExBuddy\ExBuddy\Helpers\Condition.cs:line 32
   --- End of inner exception stack trace ---
   at ExBuddy.Helpers.Condition.AddNamespacesToScriptManager(String[] param)
   at ExBuddy.OrderBotTags.Behaviors.ExProfileBehavior..cctor() in C:\Users\pc\Desktop\RB\BotBases\ExBuddy\ExBuddy\OrderBotTags\Behaviors\ExProfileBehavior.cs:line 29 --> System.InvalidOperationException: The calling thread cannot access this object because a different thread owns it.
   at System.Windows.Threading.Dispatcher.VerifyAccess()
   at System.Windows.Window.get_Title()
   at ExBuddy.Helpers.Condition..cctor() in C:\Users\pc\Desktop\RB\BotBases\ExBuddy\ExBuddy\Helpers\Condition.cs:line 32
```

I have ExBuddy installed from your link, and also tried joining your discord but the link shows invalid.

What can I do?

**Comment by Angles24** [comment]
ExBuddy is suppose to be in the "Plugins" folder not "Botbase"

**Comment by mr-jak3z** [comment]
Ok, that's embarrassing, I don't know how I ended up doing that. Do you still have a discord server I can join in case of any other questions so I avoid posting here?

**Comment by Angles24** [comment]
https://discord.com/invite/bmgCq39

Thanks for letting me know about the discord link, I have updated it.
